"""add risk_zones and risk_zone_cells tables

Revision ID: 861a0419ccf8
Revises: 
Create Date: 2026-03-29 20:47:36.724240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '861a0419ccf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kommune_id', sa.Integer(), nullable=False),
    sa.Column('climate_type', postgresql.ENUM('HEAT', 'HEAVY_RAIN', 'RIVER_FLOOD', 'DROUGHT', 'FOREST_FIRE', 'AGRICULTURE', 'STORMS', 'SEA_LEVEL', 'HEALTH', name='climatetype', create_type=False), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('zone_index', sa.Integer(), nullable=False),
    sa.Column('cell_count', sa.Integer(), nullable=False),
    sa.Column('mean_risk', sa.Float(), nullable=False),
    sa.Column('max_risk', sa.Float(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kommune_id'], ['kommunen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kommune_id', 'climate_type', 'level', 'zone_index', name='uq_risk_zone_kommune_type_level_idx')
    )
    op.create_index(op.f('ix_risk_zones_id'), 'risk_zones', ['id'], unique=False)
    op.create_table('risk_zone_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_zone_id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_zone_id'], ['risk_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_zone_cells_id'), 'risk_zone_cells', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_zone_cells_id'), table_name='risk_zone_cells')
    op.drop_table('risk_zone_cells')
    op.drop_index(op.f('ix_risk_zones_id'), table_name='risk_zones')
    op.drop_table('risk_zones')
    # ### end Alembic commands ###
